# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='role',
        ),
        migrations.AddField(
            model_name='roles',
            name='department_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='store_manager',
            field=models.BooleanField(default=True),
        ),
    ]
