# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('vendor', models.CharField(max_length=64)),
                ('batch_num', models.IntegerField()),
                ('price', models.IntegerField()),
                ('batch_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=16)),
            ],
        ),
    ]
