# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='status',
            field=models.CharField(max_length=64),
        ),
    ]
